spring:
  application:
    name: coupon-service

  datasource:
    url: jdbc:h2:mem:coupondb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        ddl-auto: update
        format_sql: true
    show-sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

# Actuator 설정
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    tags:
      application: ${spring.application.name}
  tracing:
    propagation:
      type: w3c
    enabled: true
    sampling:
      probability: 1.0

# 로깅 설정
logging:
  level:
    root: info
    com.example: debug
  file:
    path: ./logs
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"