server:
  http_listen_port: 3100
  http_server_read_timeout: 3m
  http_server_write_timeout: 3m
  grpc_server_max_send_msg_size: 2147483647
  grpc_server_max_recv_msg_size: 2147483647

common:
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

ruler:
  enable_api: true

limits_config:
  reject_old_samples: true
  reject_old_samples_max_age: 168h
  split_queries_by_interval: 15m
  allow_structured_metadata: false